In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2) #range, start, stop, step

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(4) #Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.46126145, 0.08983155, 0.452332  , 0.78140831, 0.91629643])

In [15]:
np.random.rand(5,5)

array([[0.51643968, 0.6919279 , 0.23152722, 0.5277138 , 0.5654061 ],
       [0.8755756 , 0.4484194 , 0.11341377, 0.24204569, 0.6189369 ],
       [0.67883119, 0.24607721, 0.73299117, 0.5126415 , 0.68396067],
       [0.60177086, 0.22176794, 0.81443174, 0.80623756, 0.92892733],
       [0.40025654, 0.44941093, 0.22521935, 0.99073842, 0.61243238]])

In [16]:
np.random.randn(4,4)

array([[ 0.75969995, -1.69050934,  0.35678596, -0.33144537],
       [-1.77716739, -1.13999742, -0.16750566,  0.46912181],
       [ 0.24746071,  2.20925329, -0.52386793,  1.02845972],
       [-0.05909012,  0.16281428,  0.46075331,  0.45333982]])

In [17]:
np.random.randint(1,100,10)

array([25, 43, 69, 86, 97, 60, 49, 60,  8, 24])

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
ranarr

array([25, 31,  3, 45, 26, 12, 22,  0,  3, 38])

In [22]:
ranarr.reshape(5,2)

array([[25, 31],
       [ 3, 45],
       [26, 12],
       [22,  0],
       [ 3, 38]])

In [23]:
ranarr.max()

45

In [24]:
ranarr.argmax()

3

In [25]:
ranarr

array([25, 31,  3, 45, 26, 12, 22,  0,  3, 38])

In [26]:
arr.shape

(25,)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr = arr.reshape(5,5)

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.shape

(5, 5)

In [32]:
arr.dtype

dtype('int32')

In [33]:
arr.max()

24

In [34]:
arr.argmax() # returns the index location of the maximum value

24

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[8]

8

In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
arr[0:5]  = 100 #Broadcast the value to the first 4 values

In [45]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0,11)

In [50]:
slice_of_arr = arr[0:6]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy = arr.copy()

In [56]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# 2d Array..

In [61]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0][0] #row then column for digit 5

5

In [65]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
#element 25
arr_2d[1][1]

25

In [68]:
arr_2d[2][1]

40

In [69]:
arr_2d[2,1] #single bracket notation

40

In [70]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr = np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr] #returns the true values

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr<3]

array([1, 2])

In [79]:
arr_2d = np.arange(50).reshape(5,10)

In [80]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [83]:
arr3 = np.arange(0,11)

In [84]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr3 + arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [86]:
arr3 - arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr3* arr3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
1/0.000000001


999999999.9999999

In [89]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
arr3/arr3

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
np.sqrt(arr3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [94]:
np.max(arr3)

10

In [95]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])